<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<RootNamespace>Backend</RootNamespace>
		<AssemblyName>Minstrel</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\FileSystem\FileSystem.csproj" />
		<ProjectReference Include="..\Network\Network.csproj" />
	</ItemGroup>

</Project>
