<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Blazor.LocalStorage" Version="9.0.1" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
      <PackageReference Include="TagLibSharp" Version="2.3.0" />
    </ItemGroup>

</Project>
